import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/common/NavbarWrapper";
import Footer from "@/components/common/Footer";
import { getNavbar } from "@/lib/queries/navbarData";
import { getFooter } from "@/lib/queries/footerData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [navbarData, footerData] = await Promise.all([
    getNavbar(),
    getFooter()
  ])

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        >
        <NavbarWrapper navbarData={navbarData} />

        <main className="flex-grow">
          {children}
        </main>

        <Footer footerData={footerData} />
      </body>
    </html>
  );
}
