import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/common/NavbarWrapper";
import { getNavbar } from "@/lib/queries/navbarData";
import { getTheme } from "@/lib/queries/colorPalettQuery";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navbarData = await getNavbar()
  const theme = await getTheme();
  const bg = theme.background.homebg || "";
  const solidBg = bg.match(/#[a-fA-F0-9]{3,6}/)?.[0] || bg;

  return (
    <html lang="en"
    style={{ background: solidBg, }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarWrapper navbarData={navbarData} />

        {children}
      </body>
    </html>
  );
}
